anchor:
  # Fair baseline (protected) keys
  ce_alpha: 0.65
  kd_alpha: 0.35
  kd_target: avg
  tau: 4.0
  ce_label_smoothing: 0.05

  optimizer: sgd
  student_lr: 0.1
  student_weight_decay: 0.0005

  dataset:
    batch_size: 128

  mixup_alpha: 0.2
  cutmix_alpha_distill: 0.0

  use_partial_freeze: false
  student_freeze_bn: false

  # Validation controls
  strict_mode: true
  auto_renorm: false

