name: asib
ce_alpha: 0.3
kd_alpha: 0.7  # KD 손실 활성화
kd_ens_alpha: 0.0

# IB 설정
use_ib: true                    # IB 손실 활성화
ib_beta: 0.01                  # IB 손실 가중치
feat_kd_alpha: 0.1             # Feature KD 활성화

# KD 타겟 설정
kd_target: "synergy"            # "synergy", "avg", "weighted_conf"
teacher_weights: [0.4, 0.6]     # [R152, ConvNeXt-S] 성능 기반 가중치

# Distillation Adapter
use_distillation_adapter: true  # Distillation Adapter 사용

# Uncertainty weighting
min_cw: 0.1                     # 최소 certainty weight
