# configs/model/student/resnet152_progfreeze.yaml

model:
  student:
    name: resnet152
    pretrained: true      # ✔️  사전학습
    lr: 8e-4
    weight_decay: 8e-4
    freeze_level: -1      # 초기값 (Stage‑0)
    freeze_bn: false
    use_adapter: true

# ---------------- experiment overrides ----------------
student_freeze_schedule: [-1, 2, 1, 0]    # Stage0~3
student_epochs_schedule:  [20, 15, 15, 15]  # Stage0 더 길게
num_stages: 4
use_partial_freeze: true
