# configs/model/student/resnet152_scratch.yaml

model:
  student:
    name: resnet152
    pretrained: false
    lr: 5e-4
    weight_decay: 8e-4
    freeze_level: 1          # head + layer4만 학생
    freeze_bn: false
    use_adapter: true
