# configs/model/student/resnet50_pretrain.yaml

model:
  student:
    name: resnet50
    pretrained: true
    lr: 8e-4
    weight_decay: 8e-4
    freeze_level: 1         # head + layer4
    freeze_bn: false
    use_adapter: true
