name: Test

on:
  push:
    paths: ['**.py', '.github/workflows/**']
  pull_request:
    paths: ['**.py', '.github/workflows/**']

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -v
